// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwX5tH4_zblhK5qut1ZHLS4dwMxovdkc',
    appId: '1:768491054932:web:4e236493b8a52482698ac1',
    messagingSenderId: '768491054932',
    projectId: 'traveller-380414',
    authDomain: 'traveller-380414.firebaseapp.com',
    storageBucket: 'traveller-380414.appspot.com',
    measurementId: 'G-2P3FL12V2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHzr0FhlauM8V6LXY06VToTLfvD45b68',
    appId: '1:768491054932:android:11465b8f242fa9a3698ac1',
    messagingSenderId: '768491054932',
    projectId: 'traveller-380414',
    storageBucket: 'traveller-380414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWZUOhiydCD3i6rIkEXQ0AcdbA0lH3hc',
    appId: '1:768491054932:ios:2fb5b752a18ab136698ac1',
    messagingSenderId: '768491054932',
    projectId: 'traveller-380414',
    storageBucket: 'traveller-380414.appspot.com',
    iosBundleId: 'com.example.traveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWZUOhiydCD3i6rIkEXQ0AcdbA0lH3hc',
    appId: '1:768491054932:ios:ee7b81db5d45c93c698ac1',
    messagingSenderId: '768491054932',
    projectId: 'traveller-380414',
    storageBucket: 'traveller-380414.appspot.com',
    iosBundleId: 'com.example.traveler.RunnerTests',
  );
}
